### PR TITLE
!!! Various commits

### PR DESCRIPTION
**Pull request by HardeepAsrani**
See the commits for info. @rodica-andronache

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@HardeepAsrani I think you deleted the repo or something http://prntscr.com/cec5yv . Can you please check?

**Comment by HardeepAsrani** [comment]
@rodica-andronache No idea where it went. you can just add the commits manually. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani ok, I made the changes. But next time, I will have to ask you to do it :)

**Comment by HardeepAsrani** [comment]
@rodica-andronache Sure, it doesn't take time. I can always use the .patch file.

**Pull request closed without merging**
